EXTRA_VENDOR_LIBRARIES := \
    android.frameworks.schedulerservice@1.0 \
    android.frameworks.sensorservice@1.0 \
    android.hardware.audio.common@2.0 \
    android.hardware.audio.common@2.0-util \
    android.hardware.audio.effect@2.0 \
    android.hardware.audio@2.0 \
    android.hardware.biometrics.fingerprint@2.1 \
    android.hardware.bluetooth@1.0 \
    android.hardware.broadcastradio@1.0 \
    android.hardware.broadcastradio@1.1 \
    android.hardware.camera.common@1.0 \
    android.hardware.camera.device@1.0 \
    android.hardware.camera.device@3.2 \
    android.hardware.camera.provider@2.4 \
    android.hardware.configstore@1.0 \
    android.hardware.contexthub@1.0 \
    android.hardware.gatekeeper@1.0 \
    android.hardware.gnss@1.0 \
    android.hardware.graphics.allocator@2.0 \
    android.hardware.ir@1.0 \
    android.hardware.keymaster@3.0 \
    android.hardware.light@2.0 \
    android.hardware.memtrack@1.0 \
    android.hardware.power@1.0 \
    android.hardware.radio.deprecated@1.0 \
    android.hardware.radio@1.0 \
    android.hardware.sensors@1.0 \
    android.hardware.soundtrigger@2.0 \
    android.hardware.thermal@1.0 \
    android.hardware.tv.cec@1.0 \
    android.hardware.tv.input@1.0 \
    android.hardware.vibrator@1.0 \
    android.hardware.vr@1.0 \
    android.hardware.wifi.supplicant@1.0 \
    android.hardware.wifi@1.0 \
    android.hidl.allocator@1.0 \
    android.hidl.memory@1.0 \
    android.system.wifi.keystore@1.0 \
    android.hardware.dumpstate@1.0 \
    libLLVM \
    libbcinfo \
    libandroid_runtime \
    libandroidfw \
    libappfuse \
    libaudioclient \
    libaudioutils \
    libavservices_minijail \
    libbase \
    libbcc \
    libbinder \
    libbm \
    libcamera_client \
    libcamera_metadata \
    libcrypto \
    libeng-audio \
    libengbt \
    libexpat \
    libfmjni \
    libfmq \
    libgatekeeper \
    libgui \
    libhardware_legacy \
    libhidlbase \
    libhidlmemory \
    libhidltransport \
    libhwbinder \
    libhwui \
    libinput \
    libinputflinger \
    libinputservice \
    libjpeg \
    libkeymaster_portable \
    libkeymaster_messages \
    libkeystore_binder \
    libmedia \
    libnativehelper \
    libnbaio \
    libnetutils \
    libnl \
    libpixelflinger \
    libpng \
    libpower \
    libpowermanager \
    libprotobuf-cpp-lite \
    libradio_metadata \
    librilutils \
    libschedulerservicehidl \
    libsensorservice \
    libsensorservicehidl \
    libskia \
    libsoftkeymasterdevice \
    libspeexresampler \
    libsqlite \
    libssl \
    libsuspend \
    libtinyalsa \
    libui \
    libusbhost \
    libwebrtc_audio_preprocessing \
    libwifi-system \
    android.hardware.configstore-utils \
    liblzma \
    libnativebridge \
    libnativeloader \
    libsensor \
    libunwind \
    libziparchive \
    libmemtrack  \
    libdebuggerd_client \
    libETC1 \
    libselinux \
    libharfbuzz_ng \
    libpdfium \
    libimg_utils \
    libnetd_client \
    libsoundtrigger \
    libprocessgroup \
    libmemunreachable \
    libvintf \
    libdrm \
    libEGL_POWERVR_ROGUE \
    libGLESv1_CM_POWERVR_ROGUE \
    libGLESv2_POWERVR_ROGUE \
    memtrack.generic \
    libcreatesurface \
    libglslcompiler \
    libIMGegl \
    libpvrANDROID_WSEGL \
    libPVRScopeServices \
    libsrv_um \
    libsutu_display \
    libusc \
    libPVRRS \
    libPVRRS.sha1 \
    libdrmframework \
    libaudiomanager \
    libprotobuf-cpp-full \
    libft2 \
    libminikin \
    libRScpp \
    libleakdetect \
    libsonivox \
    libmedia_helper \
    libmediadrm \
    libmediametrics \
    android.hidl.token@1.0-utils \
    libdng_sdk \
    libpiex \
    android.hardware.graphics.bufferqueue@1.0 \
    android.hardware.media@1.0

#EXTRA_VENDOR_LIBRARIES += \
#    libengfm \
#    libradio

